CREATE DATABASE Agendamento;

CREATE TABLE Sala (
    Id INT NOT NULL AUTO_INCREMENT,
	Descricao VARCHAR(100) NOT NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE Agendamento (
    Id INT NOT NULL AUTO_INCREMENT,
	IdSala INT NOT NULL,
	EmailRequisitante VARCHAR(100),
	DataHoraInicio DATETIME NOT NULL,
	DataHoraFim DATETIME NOT NULL,
	Situacao VARCHAR(20) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,	
    PRIMARY KEY (Id),
	FOREIGN KEY (IdSala) REFERENCES Sala(Id)
);